In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
data = pd.read_csv('train.csv')
data1 = pd.read_csv('test.csv', error_bad_lines=False)
X = data.iloc[:, 0:34].values
y = data.iloc[:, 34].values.reshape(-1,1)

b'Skipping line 41: expected 34 fields, saw 35\nSkipping line 43: expected 34 fields, saw 35\nSkipping line 44: expected 34 fields, saw 35\nSkipping line 51: expected 34 fields, saw 35\nSkipping line 81: expected 34 fields, saw 35\nSkipping line 83: expected 34 fields, saw 35\nSkipping line 89: expected 34 fields, saw 35\nSkipping line 90: expected 34 fields, saw 35\nSkipping line 91: expected 34 fields, saw 35\nSkipping line 92: expected 34 fields, saw 35\n'


In [3]:
from sklearn.preprocessing import OneHotEncoder
ONE = OneHotEncoder()
X1 = X[:, 9].reshape(-1, 1)
X1 = ONE.fit_transform(X1).toarray()

X2 = X[:, 10].reshape(-1, 1)
X2 = ONE.fit_transform(X2).toarray()

X3 = X[:, 11].reshape(-1, 1)
X3 = ONE.fit_transform(X3).toarray()

X4 = X[:, 8].reshape(-1, 1)
X4 = ONE.fit_transform(X4).toarray()

X5 = X[:, 7].reshape(-1, 1)
X5 = ONE.fit_transform(X5).toarray()

X6 = X[:, 6].reshape(-1, 1)
X6 = ONE.fit_transform(X6).toarray()

X = np.c_[X6, X5, X4, X1, X2, X3, X[:, [23, 24]], X[:, 26:32], X[:, 33]]

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.1, random_state = 0)

In [5]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [6]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', gamma = 0.032, C =0.69, random_state = 0)
classifier.fit(X_train, y_train)

Z = data1.iloc[:, :].values

Z1 = Z[:,9].reshape(-1,1)
Z1 = ONE.fit_transform(Z1).toarray()

Z2 = Z[:,10].reshape(-1,1)
Z2 = ONE.fit_transform(Z2).toarray()

Z3 = Z[:,11].reshape(-1,1)
Z3 = ONE.fit_transform(Z3).toarray()

Z4 = Z[:,8].reshape(-1,1)
Z4 = ONE.fit_transform(Z4).toarray()

Z5 = Z[:,7].reshape(-1,1)
Z5 = ONE.fit_transform(Z5).toarray()

Z6 = Z[:,6].reshape(-1,1)
Z6 = ONE.fit_transform(Z6).toarray()


Z = np.c_[Z6, Z5, Z4, Z1, Z2, Z3, Z[:, [23, 24]], Z[:, 26:32], Z[:, 33]]
print(Z)

Z_pred = classifier.predict(Z)

print(Z_pred)

[[0.0 0.0 0.0 ... 0 0 0]
 [0.0 0.0 0.0 ... 0 0 0]
 [0.0 0.0 0.0 ... 0 0 0]
 ...
 [0.0 0.0 0.0 ... 0 0 1]
 [0.0 0.0 0.0 ... 0 0 0]
 [0.0 0.0 0.0 ... 0 0 1]]


/root/anaconda3/envs/env01/lib/python3.7/site-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


ValueError: X.shape[1] = 49 should be equal to 54, the number of features at training time